public with sharing class CoCData {
    @AuraEnabled
    public String identifier;
    @AuraEnabled
    public String branchIdentifier;
    @AuraEnabled
    public String rsin;
    @AuraEnabled
    public String activeIcon;
    @AuraEnabled
    public String mainIcon;
    @AuraEnabled
    public String name;
    @AuraEnabled
    public String street;
    @AuraEnabled
    public String houseNumber;
    @AuraEnabled
    public String houseNumberAddition;
    @AuraEnabled
    public String postalCode;
    @AuraEnabled
    public String city;
    @AuraEnabled
    public String country;
    @AuraEnabled
    public Boolean isBranch;
    @AuraEnabled
    public Boolean isMainBranch;
}